### ISSUE TITLE
Json array iterator not yielding correct values

### ISSUE THREAD

**Issue by ghost** [OpenSystemsLab/sam.nim#1]
The following:

```
import sam

let data = """{
    "layers": [2,2,1],
   }"""

let dat = parse(data)
for n in dat["layers"]:
   echo n
```

echoes `[2,2,1]\n2\n` which seems not correct.

**Comment by ghost** [comment]
Please bump the version of this package to fix the issue.

**Comment by ba0f3** [comment]
what version you are using? is it resolved with latest commit? 
im sorry but I didnt have time to check this case yet

**Comment by ba0f3** [comment]
oh I see I fixed it long time ago, thank you!
