### ISSUE TITLE
Is it work with Option?

### ISSUE THREAD

**Issue by gabbhack** [OpenSystemsLab/sam.nim#4]
```nim
import options
import sam

type
  Test = object
    id: Option[int]

let t = Test(id: some(123))
echo t.dumps()
```
Current output:
```
{"id":{"val":123,"has":true}}
```
Expected output:
```
{"id":123}
```

**Comment by ba0f3** [comment]
Option is an object, so it wont works as you expected. even stdlib can't do it

**Comment by gabbhack** [comment]
It works as expected with stdlib: https://play.nim-lang.org/#ix=2CNT
I guess this is because of the special handling of the Option type
https://nim-lang.org/docs/json.html#overview-unmarshalling
https://nim-lang.org/docs/json.html#%25%2COption%5BT%5D

**Comment by ba0f3** [comment]
oh yes, it works with `json`, I were compare to `marshal`. I will try to add `Option` support soon when I have spare time.
If you can make it happens, PR is welcome. Thanks!
