### ISSUE TITLE
new(target) if it's the ref type

### ISSUE THREAD

**Issue by gabbhack** [OpenSystemsLab/sam.nim#6]
[Earlier](https://github.com/OpenSystemsLab/sam.nim/issues/2) I wrote about the fact that sam does not create a new object itself if the type is a reference one.
To avoid this error, we have to manually create an object using `new`, but if we have a large object with many fields, it becomes difficult to create objects manually.
```nim
import sam

type
  Foo = ref object
    text: string
  Test = object
    foo: Foo

var t: Test
# new t.foo
loads(t, """{"foo": {"text": "123"}}""")
echo t.foo.text
```
If you don't use new, the program will fail. 

I suggest making similar changes: https://github.com/gabbhack/sam.nim/commit/f0af9f4dae4ec430c481f8c90ba6540d3008ebe6

**Comment by ba0f3** [comment]
Thank you, I will fix it  soon
